/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2020-11-19 09:05:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <title>Deccan Sport Club</title>\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Raleway:400,500,700|Roboto:400,900\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link defer href=\"assets/css/styles.css\" rel=\"stylesheet\"> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- ======= Hero Section ======= -->\r\n");
      out.write("  <section class=\"hero\">\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-5\">\r\n");
      out.write("          <a class=\"hero-brand\">         \r\n");
      out.write("          <h1> Deccan Sport Club</h1>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-5\">\r\n");
      out.write("        <h3>\r\n");
      out.write("         A All-Rounder's Club\r\n");
      out.write("        </h3>\r\n");
      out.write("        <p class=\"tagline\">\r\n");
      out.write("          We INVEST In To Your INTEREST\r\n");
      out.write("        </p>\r\n");
      out.write("        \r\n");
      out.write("        <a class=\"btn btn-full scrollto\" href=\"");
      out.print(request.getContextPath());
      out.write("/register.jsp\">Get Started With Us</a>\r\n");
      out.write("          <a class=\"btn btn-full scrollto\" href=\"");
      out.print(request.getContextPath());
      out.write("/AppServlet\">LogIn</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </section><!-- End Hero --> \r\n");
      out.write("\r\n");
      out.write("    <!-- ======= About Section ======= -->\r\n");
      out.write("    <section class=\"about\" id=\"about\">\r\n");
      out.write("      <div class=\"container\" >\r\n");
      out.write("        <div class=\"row stats-row\">\r\n");
      out.write("          <div class=\"stats-col text-center col-md-3 col-sm-6\">\r\n");
      out.write("         \r\n");
      out.write("            <div class=\"circle\" pl-4>\r\n");
      out.write("             <a> <img class=\"circle1\" src=\"assets/img/cricket.jpg\" ></a>\r\n");
      out.write("              <span class=\"stats-no\" data-toggle=\"counter-up\">Cricket</span> \r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"circle\" pl-4>\r\n");
      out.write("             <a> <img class=\"circle1\" src=\"assets/img/football.jpg\" ></a>\r\n");
      out.write("              <span class=\"stats-no\" data-toggle=\"counter-up\">Football</span> \r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"circle\" pl-4>\r\n");
      out.write("             <a> <img class=\"circle1\" src=\"assets/img/vollyball.jpg\" ></a>\r\n");
      out.write("              <span class=\"stats-no\" data-toggle=\"counter-up\">Vollyball</span> \r\n");
      out.write("            </div>  \r\n");
      out.write("            <div class=\"circle\" pl-4>\r\n");
      out.write("             <a> <img class=\"circle1\" src=\"assets/img/football.jpg\" ></a>\r\n");
      out.write("              <span class=\"stats-no\" data-toggle=\"counter-up\">Football</span> \r\n");
      out.write("            </div>\r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section><!-- End About Section -->\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer class=\"site-footer\">\r\n");
      out.write("    <div class=\"bottom\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-6 col-xs-12 text-lg-left text-center\">\r\n");
      out.write("            <p class=\"copyright-text\">\r\n");
      out.write("              &copy; Copyright <strong>FET-JAVA-2020-G-2</strong>. All Rights Reserved\r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("          </div>       \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JS, Popper.js, and jQuery -->\r\n");
      out.write("  <script src='https://kit.fontawesome.com/a076d05399.js'></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"    integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("    integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"\r\n");
      out.write("    integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\"></script>\r\n");
      out.write("  <script defer src=\"jquery-3.5.1.min.js\"></script> \r\n");
      out.write(" \r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
